[project]
name = 'Ecosystem-Preservation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ecosystem-modeling]
path = 'contracts/ecosystem-modeling.clar'
clarity_version = 2
epoch = 2.5

[contracts.extraterrestrial-species-nft]
path = 'contracts/extraterrestrial-species-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.preservation-projects]
path = 'contracts/preservation-projects.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
